name: 🚀 Deployment Request
description: Request a deployment to Terraform Cloud
title: "Deploy: "
labels: ["deploy"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Deployment Request
        
        Please fill in the following information to trigger a deployment:
  
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select the target environment
      options:
        - nonprod
        - prod
      required: true
  
  - type: input
    id: tfc_organization
    attributes:
      label: TFC Organization
      description: Terraform Cloud organization name
      placeholder: "your-org-name"
      required: false
  
  - type: input
    id: tfc_workspace
    attributes:
      label: TFC Workspace
      description: Terraform Cloud workspace name (optional, will use default pattern if not specified)
      placeholder: "tencent-core-network-nonprod"
      required: false
  
  - type: textarea
    id: description
    attributes:
      label: Deployment Description
      description: Additional details about this deployment
      placeholder: "Describe the purpose of this deployment..."
      required: false
  
  - type: markdown
    attributes:
      value: |
        ## 📋 Usage Instructions
        
        **Environment:** Choose between `nonprod` or `prod`
        
        **TFC Organization:** Your Terraform Cloud organization name
        - If not specified, will use the default from repository secrets
        
        **TFC Workspace:** Your Terraform Cloud workspace name
        - If not specified, will use the pattern: `tencent-core-network-{environment}`
        
        **Note:** This issue must have the `deploy` label to trigger the workflow.
